# アプリケーションにクラスタ全体の管理者権限を付与するための設定
# ServiceAccount: アプリケーションが使用するID
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa

---
# ClusterRoleBinding: ServiceAccountを既存のcluster-adminロールに紐付け
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-app-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: cluster-admin-sa
  namespace: default # ServiceAccountが存在するnamespaceを指定
roleRef:
  kind: ClusterRole
  name: cluster-admin # Kubernetesに組み込まれている管理者ロール
  apiGroup: rbac.authorization.k8s.io