# k8s/01-rbac.yaml

# アプリケーションが使用するIDとなるServiceAccountを定義
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa

---
# ServiceAccountを既存のcluster-adminロールに紐付けるClusterRoleBindingを定義
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-app-cluster-admin-binding
subjects:
- kind: ServiceAccount
  # どのIDに権限を与えるか
  name: cluster-admin-sa
  namespace: default 
roleRef:
  kind: ClusterRole
  # どのような権限を与えるか (cluster-adminは最強の権限)
  name: cluster-admin 
  apiGroup: rbac.authorization.k8s.io